// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: goodbye.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoodByeServiceClient is the client API for GoodByeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodByeServiceClient interface {
	SayGoodBye(ctx context.Context, in *SayGoodByeRequest, opts ...grpc.CallOption) (*SayGoodByeResponse, error)
}

type goodByeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodByeServiceClient(cc grpc.ClientConnInterface) GoodByeServiceClient {
	return &goodByeServiceClient{cc}
}

func (c *goodByeServiceClient) SayGoodBye(ctx context.Context, in *SayGoodByeRequest, opts ...grpc.CallOption) (*SayGoodByeResponse, error) {
	out := new(SayGoodByeResponse)
	err := c.cc.Invoke(ctx, "/proto.GoodByeService/SayGoodBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodByeServiceServer is the server API for GoodByeService service.
// All implementations must embed UnimplementedGoodByeServiceServer
// for forward compatibility
type GoodByeServiceServer interface {
	SayGoodBye(context.Context, *SayGoodByeRequest) (*SayGoodByeResponse, error)
	mustEmbedUnimplementedGoodByeServiceServer()
}

// UnimplementedGoodByeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoodByeServiceServer struct {
}

func (UnimplementedGoodByeServiceServer) SayGoodBye(context.Context, *SayGoodByeRequest) (*SayGoodByeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayGoodBye not implemented")
}
func (UnimplementedGoodByeServiceServer) mustEmbedUnimplementedGoodByeServiceServer() {}

// UnsafeGoodByeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodByeServiceServer will
// result in compilation errors.
type UnsafeGoodByeServiceServer interface {
	mustEmbedUnimplementedGoodByeServiceServer()
}

func RegisterGoodByeServiceServer(s grpc.ServiceRegistrar, srv GoodByeServiceServer) {
	s.RegisterService(&GoodByeService_ServiceDesc, srv)
}

func _GoodByeService_SayGoodBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayGoodByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodByeServiceServer).SayGoodBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GoodByeService/SayGoodBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodByeServiceServer).SayGoodBye(ctx, req.(*SayGoodByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodByeService_ServiceDesc is the grpc.ServiceDesc for GoodByeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodByeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoodByeService",
	HandlerType: (*GoodByeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayGoodBye",
			Handler:    _GoodByeService_SayGoodBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goodbye.proto",
}
